static  struct {double xtop[10];
               double xbot[10];
               double ytop[10];
               double ybot[10];
               int nlogx[10];     
               int nlogy[10];
               double xb[500];
               double yb[500];
               double dyb[500];
               int nplt[500];
               int mrk[500];
               int nbn;
               double bscl;
               double sum[10];
               double sl[10];
               double sr[10];
               double fmean;
               double sigma;
               double xsum[10];
               double x2sum[10];
               int iov;
               int ibd;}dxy;     
static  struct {int nplts[10];
                int ivcts[10];}xyft;
