###############################################################################
#
# Filename: 	Makefile
# 
# Description:	Makefile for Example Program.
#
# $Revision: 1.1.1.1 $
#
# $Date: 2005/05/24 14:34:03 $
#
# $Source: z:\\cvsroot/Linuxvme2/linuxvme_examples/Makefile,v $
#
# Copyright 2000 - 2005 Concurrent Technologies.
#
###############################################################################

# Defaults

CC 	= gcc
LIB     = libcctvme.a 
CFLAGS  = -Wall

all: example1 example2 example3 example4 example5 example6 example7

example1: example1.c
	$(CC) $(CFLAGS) $^ -o $@ $(LIB) 

example2: example2.c
	$(CC) $(CFLAGS) $^ -o $@ $(LIB) 

example3: example3.c
	$(CC) $(CFLAGS) $^ -o $@ $(LIB) 

example4: example4.c
	$(CC) $(CFLAGS) $^ -o $@ $(LIB) 

example5: example5.c
	$(CC) $(CFLAGS) $^ -o $@ $(LIB) 

example6: example6.c
	$(CC) $(CFLAGS) $^ -o $@ $(LIB) 

example7: example7.c
	$(CC) $(CFLAGS) $^ -o $@ $(LIB) 

clean:
	rm -f example1 example2 example3 example4 example5 example6 example7 
